
    py:class_<SceneParser>
    py:class_<SceneDesc>(m,"SceneDesc")
        .def(py::init<>())
    py:class_<Scene>(m, "Scene")
        .def("load_node", &Scene::load_node)
        .def("load_camera", &Scene::load_camera)
        .def("load_film", &Scene::load_film)
        .def("load_filter", &Scene::load_filter)
        .def("load_integrator", &Scene::load_integrator)
        .def("load_surface", &Scene::load_surface)
        .def("load_light", &Scene::load_light)
        .def("load_sampler", &Scene::load_sampler)
        .def("load_shape", &Scene::load_shape)
        .def("load_transform", &Scene::load_transform)
        .def("load_light_sampler", &Scene::load_light_sampler)
        .def("load_environment", &Scene::load_environment)
        .def("load_texture", &Scene::load_texture)
        .def("load_texture_mapping", &Scene::load_texture_mapping)
        .def("load_spectrum", &Scene::load_spectrum)
        .def("load_medium", &Scene::load_medium)
        .def("load_phase_function", &Scene::load_phase_function)